Repository s-katte/Sketchify, pull requests merged in 2020-10, with the labels that each got.

#6 add contributing.md. Fixes #5
  CONTRIBUTING.md
Labels: accepted

#9 Doc: updated CONTRIBUTING.md according to project.
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#10 Feat: Resizable windows
  package-lock.json
  package.json
  src/components/App.js
  src/components/Editor.js
  src/index.css
Labels: hacktoberfest-accepted

#12 Doc: Update Readme.md
  README.md
  README.old.md
  src/Screenshots/ss-1.png
Labels: hacktoberfest-accepted

#16 Feat: Alert the user before closing tab/window
  src/components/App.js
Labels: under-review

#17 Install prettier and setup actions
  .eslintignore
  .github/workflows/eslint.yml
  .github/workflows/prettier.yml
  .perttierrc.json
  .prettierignore
  package-lock.json
  package.json
Labels: hacktoberfest-accepted

#29 Added pull request template
  .github/pull_request_template.md
Labels: hacktoberfest-accepted

#41 Added Scroll Bar
  src/index.css
Labels: under-review

#37 [Feat]: Issue #14 - Add Verdana Base Font Family
  src/index.css
Labels: under-review

#44 Added Code_Of_Conduct.md
  CODE_OF_CONDUCT.md
Labels: under-review

#46 [Feat] Add suggestion and autoclose tag, bracket while writing code
  src/components/App.js
  src/components/Editor.js
Labels: under-review

#49 [Feat] Add Clear Code button
  src/components/App.js
  src/index.css
Labels: under-review
